SELECT @@GLOBAL.sql_mode global, @@SESSION.sql_mode session;
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
SET SESSION sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- Berita
ALTER TABLE `t_berita`
ADD COLUMN `slug` varchar(255) DEFAULT NULL AFTER `title`,
ADD COLUMN `created_at` datetime DEFAULT NULL,
ADD COLUMN `created_by` int(11) DEFAULT NULL,
ADD COLUMN `updated_at` datetime DEFAULT NULL,
ADD COLUMN `updated_by` int(11) DEFAULT NULL;

ALTER TABLE  `t_berita` DROP PRIMARY KEY;
ALTER TABLE `t_berita` ADD CONSTRAINT unique_id UNIQUE (`id`);
ALTER TABLE `t_berita` ADD COLUMN pk INT PRIMARY KEY AUTO_INCREMENT AFTER id;

ALTER TABLE `t_berita` MODIFY COLUMN `category` varchar(50) NOT NULL DEFAULT 'Berita';
ALTER TABLE `t_berita` MODIFY COLUMN `language` varchar(10) NOT NULL DEFAULT 'id';
ALTER TABLE `t_berita` MODIFY COLUMN `newsdate` date DEFAULT NULL;
ALTER TABLE `t_berita` MODIFY COLUMN `updateddate` datetime DEFAULT NULL;